title: CJ Dunteman
logo: /assets/images/me.jpeg
description: Hi! I'm CJ. I am a student at the University of Wisconsin - Madison majoring in Computer Science. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
theme: minima

plugins:
  - jekyll-feed