title: CJ Dunteman
logo: /assets/images/me.jpeg
description: Hi! I'm CJ. I am a student at the University of Wisconsin - Madison majoring in Computer Science. On this website you can find out more about me. 
show_downloads: "true"
google_analytics:
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# feed:
#   path: atom.xml

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"