name: Dependabot
on: 
  pull_request:
    branches:
      - main

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: America/Chicago
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: America/Chicago
